services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-transactions_db}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "${DB_PORT:-5432}:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - PORT=${BACKEND_PORT:-3000}
    environment:
      PORT: ${BACKEND_PORT:-3000}
      DB_HOST: ${DB_HOST:-db}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_NAME:-transactions_db}
      DB_PORT: ${DB_PORT:-5432}
      API_URL: ${API_URL:-http://localhost:3000}
    ports:
      - "${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - PORT=${FRONTEND_PORT:-80}
        - API_URL=${API_URL:-http://localhost:3000}
    environment:
      PORT: ${FRONTEND_PORT:-80}
      API_URL: ${API_URL:-http://localhost:3000}
    ports:
      - "${FRONTEND_PORT:-80}:${FRONTEND_PORT:-80}"
    depends_on:
      - backend

volumes:
  postgres_data:
