name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  POSTGRES_DB: transactions_db
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64] # Builds in parallel

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version and increment patch
        id: get_version
        run: |
          # Get base version from package.json
          PKG_VERSION=$(node -p "require('./package.json').version")

          # Extract major and minor version
          MAJOR_MINOR=$(echo $PKG_VERSION | cut -d. -f1,2)

          # Get latest git tag
          LATEST_TAG=$(git tag -l "v${MAJOR_MINOR}.*" | sort -V | tail -n 1)

          if [ -z "$LATEST_TAG" ]; then
            PATCH=0
          else
            CURRENT_PATCH=$(echo $LATEST_TAG | cut -d. -f3)
            PATCH=$((CURRENT_PATCH + 1))
          fi

          # Set new version
          NEW_VERSION="${MAJOR_MINOR}.${PATCH}"
          echo "VERSION=${NEW_VERSION}" >> $GITHUB_ENV

          # Create and push new tag
          git tag "v${NEW_VERSION}"
          git push origin "v${NEW_VERSION}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          use: true
          driver: docker-container

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/db
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest
            type=ref,event=branch
      - name: Build and push Docker images
        uses: docker/bake-action@v2
        with:
          files: ./docker-bake.hcl
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
            db.build-args.POSTGRES_DB=${{ env.POSTGRES_DB }}
            db.build-args.POSTGRES_USER=${{ env.POSTGRES_USER }}
            db.build-args.POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}
            backend.build-args.DB_HOST=db
            backend.build-args.DB_USER=${{ env.POSTGRES_USER }}
            backend.build-args.DB_PASSWORD=${{ env.POSTGRES_PASSWORD }}
            backend.build-args.DB_NAME=${{ env.POSTGRES_DB }}
            backend.build-args.DB_PORT=5432
            frontend.build-args.API_URL=http://localhost:3000
